# Generated by Django 5.1.4 on 2025-02-14 23:58

import django.utils.timezone
import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('applied_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('experience', models.IntegerField(default=0)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Shortlisted for Interview', 'Shortlisted for Interview'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('interview_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('interview_venue', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'ordering': ['-applied_on'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('skills_required', models.TextField()),
                ('min_salary', models.DecimalField(decimal_places=2, help_text='Minimum salary in LPA', max_digits=6)),
                ('max_salary', models.DecimalField(decimal_places=2, help_text='Maximum salary in LPA', max_digits=6)),
                ('location', models.CharField(choices=[('Mumbai', 'Mumbai'), ('Vasai', 'Vasai')], max_length=255)),
                ('job_type', models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('RM', 'Remote')], max_length=2)),
                ('category', models.CharField(choices=[('Software Developer', 'Software Developer'), ('Designer', 'Designer'), ('Marketing', 'Marketing'), ('Service', 'Service'), ('Teacher', 'Teacher'), ('Finance', 'Finance'), ('Data Analyst', 'Data Analyst'), ('Content Writer', 'Content Writer'), ('Sales', 'Sales'), ('Customer Support', 'Customer Support'), ('Engineering', 'Engineering'), ('Human Resources', 'Human Resources')], default='Software Developer', max_length=50)),
                ('expiry_date', models.DateField(default=jobs.models.get_default_expiry_date)),
                ('min_experience', models.PositiveIntegerField(default=0)),
                ('max_experience', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vacancies', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-added_on'],
            },
        ),
    ]
